# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.define :node1 do |node1|

    node1.vm.provider :aws do |aws, override|
      override.vm.box = "dummy"
      override.vm.box_url = 'https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box'
      override.nfs.functional = false
      aws.access_key_id = ENV['AWS_ACCESS_KEY_ID']
      aws.secret_access_key = ENV['AWS_SECRET_ACCESS_KEY']
      aws.keypair_name = ENV['AWS_KEYPAIR_NAME']
      aws.ami = "ami-d114f295"
      aws.region = "us-west-1"
      aws.instance_type = "t2.large"
      override.ssh.username = "ec2-user"
      override.ssh.private_key_path = ENV['PRIVATE_AWS_SSH_KEY_PATH']
      aws.security_groups = ['sg-0072fd65']
#      aws.block_device_mapping = [{ 'DeviceName' => '/dev/sda1', 'Ebs.VolumeSize' => 60 }]
      aws.subnet_id = 'subnet-b0f2a1f6'
      aws.private_ip_address = '172.31.1.20'
    end #aws
  end  #node1

  config.ssh.pty

  config.vm.provision :shell, :path => File.expand_path('~/Development/puppet/puppet-bootstrap/centos_6_x.sh')

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "./manifests"
    puppet.module_path = File.expand_path("~/Development/puppet/modules")
    puppet.options = ['--verbose']
  end

end
